---
engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      extensions:
        - .js

    checks:
      import/no-duplicates:
        enabled: false

      no-template-curly-in-string:
        enabled: false

      import/no-unresolved:
        enabled: false

      import/no-extraneous-dependencies:
        enabled: false

      import/no-named-as-default-member:
        enabled: false

  stylelint:
    enabled: true

ratings:
  paths:
  - "**.js"

exclude_paths:
  - __tests__/**/*
  - .vscode/**/*
  - android/**/*
  - ios/**/*
  - node_modules/**/*