language: node_js

node_js:
  - '7'

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

before_script:
  - yarn install

script:
  - yarn test-with-coverage
  - yarn send-coverage

dist: xenial

branch:
  only:
    - master
    - homolog
